# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containerd/events/content.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from containerd.vendor.gogoproto import gogo_pb2 as containerd_dot_vendor_dot_gogoproto_dot_gogo__pb2
from containerd.protobuf.plugin import fieldpath_pb2 as containerd_dot_protobuf_dot_plugin_dot_fieldpath__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='containerd/events/content.proto',
  package='containerd.events',
  syntax='proto3',
  serialized_options=b'Z2github.com/containerd/containerd/api/events;events\240\364\036\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x63ontainerd/events/content.proto\x12\x11\x63ontainerd.events\x1a&containerd/vendor/gogoproto/gogo.proto\x1a*containerd/protobuf/plugin/fieldpath.proto\"S\n\rContentDelete\x12\x42\n\x06\x64igest\x18\x01 \x01(\tB2\xda\xde\x1f*github.com/opencontainers/go-digest.Digest\xc8\xde\x1f\x00\x42\x38Z2github.com/containerd/containerd/api/events;events\xa0\xf4\x1e\x01X\x00X\x01\x62\x06proto3'
  ,
  dependencies=[containerd_dot_vendor_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,containerd_dot_protobuf_dot_plugin_dot_fieldpath__pb2.DESCRIPTOR,])




_CONTENTDELETE = _descriptor.Descriptor(
  name='ContentDelete',
  full_name='containerd.events.ContentDelete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='digest', full_name='containerd.events.ContentDelete.digest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037*github.com/opencontainers/go-digest.Digest\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['ContentDelete'] = _CONTENTDELETE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContentDelete = _reflection.GeneratedProtocolMessageType('ContentDelete', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTDELETE,
  '__module__' : 'containerd.events.content_pb2'
  # @@protoc_insertion_point(class_scope:containerd.events.ContentDelete)
  })
_sym_db.RegisterMessage(ContentDelete)


DESCRIPTOR._options = None
_CONTENTDELETE.fields_by_name['digest']._options = None
# @@protoc_insertion_point(module_scope)
