# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from containerd.services.tasks.v1 import tasks_pb2 as containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2
from containerd.vendor.google.protobuf import empty_pb2 as containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2


class TasksStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Create',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CreateTaskRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CreateTaskResponse.FromString,
        )
    self.Start = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Start',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.StartRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.StartResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Delete',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteTaskRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteResponse.FromString,
        )
    self.DeleteProcess = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/DeleteProcess',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteProcessRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Get',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.GetRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.GetResponse.FromString,
        )
    self.List = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/List',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListTasksRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListTasksResponse.FromString,
        )
    self.Kill = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Kill',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.KillRequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Exec = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Exec',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ExecProcessRequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ResizePty = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/ResizePty',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ResizePtyRequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.CloseIO = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/CloseIO',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CloseIORequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Pause = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Pause',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.PauseTaskRequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Resume = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Resume',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ResumeTaskRequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ListPids = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/ListPids',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListPidsRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListPidsResponse.FromString,
        )
    self.Checkpoint = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Checkpoint',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CheckpointTaskRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CheckpointTaskResponse.FromString,
        )
    self.Update = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Update',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.UpdateTaskRequest.SerializeToString,
        response_deserializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Metrics = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Metrics',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.MetricsRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.MetricsResponse.FromString,
        )
    self.Wait = channel.unary_unary(
        '/containerd.services.tasks.v1.Tasks/Wait',
        request_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.WaitRequest.SerializeToString,
        response_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.WaitResponse.FromString,
        )


class TasksServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    """Create a task.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Start(self, request, context):
    """Start a process.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Delete a task and on disk state.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Kill(self, request, context):
    """Kill a task or process.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exec(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResizePty(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseIO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pause(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Resume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPids(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Checkpoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Metrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Wait(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TasksServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CreateTaskRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CreateTaskResponse.SerializeToString,
      ),
      'Start': grpc.unary_unary_rpc_method_handler(
          servicer.Start,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.StartRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.StartResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteTaskRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteResponse.SerializeToString,
      ),
      'DeleteProcess': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteProcess,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteProcessRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.DeleteResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.GetRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.GetResponse.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListTasksRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListTasksResponse.SerializeToString,
      ),
      'Kill': grpc.unary_unary_rpc_method_handler(
          servicer.Kill,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.KillRequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Exec': grpc.unary_unary_rpc_method_handler(
          servicer.Exec,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ExecProcessRequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ResizePty': grpc.unary_unary_rpc_method_handler(
          servicer.ResizePty,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ResizePtyRequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'CloseIO': grpc.unary_unary_rpc_method_handler(
          servicer.CloseIO,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CloseIORequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Pause': grpc.unary_unary_rpc_method_handler(
          servicer.Pause,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.PauseTaskRequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Resume': grpc.unary_unary_rpc_method_handler(
          servicer.Resume,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ResumeTaskRequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ListPids': grpc.unary_unary_rpc_method_handler(
          servicer.ListPids,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListPidsRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.ListPidsResponse.SerializeToString,
      ),
      'Checkpoint': grpc.unary_unary_rpc_method_handler(
          servicer.Checkpoint,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CheckpointTaskRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.CheckpointTaskResponse.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.UpdateTaskRequest.FromString,
          response_serializer=containerd_dot_vendor_dot_google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Metrics': grpc.unary_unary_rpc_method_handler(
          servicer.Metrics,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.MetricsRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.MetricsResponse.SerializeToString,
      ),
      'Wait': grpc.unary_unary_rpc_method_handler(
          servicer.Wait,
          request_deserializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.WaitRequest.FromString,
          response_serializer=containerd_dot_services_dot_tasks_dot_v1_dot_tasks__pb2.WaitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'containerd.services.tasks.v1.Tasks', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
